s={}
name=input("Enter the name")
lang=input("Enter the language")
s.update({name:lang})
name=input("Enter the name")
lang=input("Enter the language")
s.update({name:lang})
name=input("Enter the name")
lang=input("Enter the language")
s.update({name:lang})
name=input("Enter the name")
lang=input("Enter the language")
s.update({name:lang})
print(s)